# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm install, build
        run: |
          npm install
          npm install pkg
          function npm-do { (PATH=$(npm bin):$PATH; eval $@;) }
          npm-do pkg package.json --out-path output

      - name: Archive Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: output/HDS-Overlay-win.exe
          
      - name: Archive macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: output/HDS-Overlay-macos
          
      - name: Archive linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: output/HDS-Overlay-linux
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && contains(github.ref, 'refs/tags/')
    steps:
      - name: Create release draft
        uses: ncipollo/release-action@v1
        with:
            artifacts: "output/*"
            draft: true
            token: ${{ secrets.GITHUB_TOKEN }}
