name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 1 * * *' # every night at 1 am UTC
  workflow_dispatch:
    inputs:
        tags:
          description: 'Dispatch'  

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 day'
